# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '2 7,16 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: current date
      run: date
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "570302+Joolee@users.noreply.github.com"
         git config --local user.name "Joolee-CI"
         git pull
         git add README.md
         git add bing-wallpaper.md
         git add picture/*
         git add docs/*
         git add zh-cn/*
         git add ja-jp/*
         git add en-in/*
         git add pt-br/*
         git add fr-fr/*
         git add de-de/*
         git add en-ca/*
         git add en-gb/*
         git add it-it/*
         git add es-es/*
         git add fr-ca/*
         git commit -m "update readme.md"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
